#login-app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels:
    app: login-app
spec:
  selector:
    app: login-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31201
